apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: test
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: test
              servicePort: 80
            path: /
